### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by Iowerth** [jellyfin/jellyfin-webos#249]
Hi. App version 1.2.2. Server version 10.9.10. No matter what I do - subtitles do not appear from any file. I've even installed Subtitle Extract - and after it's scanning situation is the same. What should I provide to fix this? Even stock LG player displays subs correctly.

**Comment by dmitrylyzo** [comment]
> What should I provide to fix this?

1. TV model.
2. Media info.
3. Subtitles format.
4. Playback method (DirectPlay, Remux, DirectStream, Transcode).

**Comment by Iowerth** [comment]
> * TV model.
> 
> * Media info.
> 
> * Subtitles format.
> 
> * Playback method (DirectPlay, Remux, DirectStream, Transcode).

To be prepared to answer in the evening when I'll be at home, I want to provide something I know at this moment and want to clarify some points.
1. LG 65QNED876QB
2. It is about file's media info like from Total Commander plugin MediaInfo?
3. It is written when selecting subs in Jellyfin - SUBRIP. Or it is not helpful info?
4. What is it? I have server installed on Windows PC and client on LG TV, they are connected between themselves via Wi-Fi

**Comment by dmitrylyzo** [comment]
> To be prepared to answer in the evening when I'll be at home, I want to provide something I know at this moment and want to clarify some points.
> 
> 1. LG 65QNED876QB
> 2. It is about file's media info like from Total Commander plugin MediaInfo?
> 3. It is written when selecting subs in Jellyfin - SUBRIP. Or it is not helpful info?
> 4. What is it? I have server installed on Windows PC and client on LG TV, they are connected between themselves via Wi-Fi

1. So this is webOS 22.
2. Yes.
3. So this is SRT (text based).
4. You can open Player Settings (geared button) on the TV during playback and select Playback Info. There will be Play method (first line, iirc). You can also see it in the Dashboard, `(i)` button in the device widget.

> Even stock LG player displays subs correctly.

For the same video? Or in general?

**Comment by Iowerth** [comment]
> For the same video? Or in general?

For all videos. Other points will provide in the evening.

**Comment by dmitrylyzo** [comment]
More questions.
5. Do you see subtitles (for the same video) in browser on PC?
6. If Q5 is "no". I would check if the subtitles were actually extracted (iirc, `subtitles` in the cache directory). Also, maybe errors in the log.
7. If you have custom CSS or theme (skin plugin), disable it by enabling `Settings -> Display -> Disable server-provided custom CSS code` on the TV.
8. Have you tried placing the subtitles next to the video (external subtitles)?

**Comment by Iowerth** [comment]
> 4. You can open Player Settings (geared button) on the TV during playback and select Playback Info. There will be Play method (first line, iirc).

Direct Playing.
> You can also see it in the Dashboard, `(i)` button in the device widget.

There is no any `(i)` button in the device widget in the Dashboard. Just can click then edit panel appears.
> 5. Do you see subtitles (for the same video) in browser on PC?

No. (By the way Transcode is using in browser)
> 6. If Q5 is "no". I would check if the subtitles were actually extracted (iirc, `subtitles` in the cache directory). Also, maybe errors in the log.

There is no folder `subtitles` in the cache directory (`C:\ProgramData\Jellyfin\Server\cache\`). But folder `C:\ProgramData\Jellyfin\Server\data\subtitles\` is present.
> Also, maybe errors in the log.

```
[2024-09-03 20:40:15.259 +03:00] [ERR] [19] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/fcc2295f-be00-b7f2-af87-77fc0646074c/fcc2295fbe00b7f2af8777fc0646074c/Subtitles/8/0/Stream.js".
System.ArgumentException: Unsupported format: srt
```
> 7. If you have custom CSS

No, I haven't.
> 8. Have you tried placing the subtitles next to the video (external subtitles)?

External subs works fine.

Info about subs from MediaInfo:
```
Text #1
ID                          : 8
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 2 h 0 min
Bit rate                    : 47 b/s
Frame rate                  : 0.118 FPS
Count of elements           : 857
Stream size                 : 41.8 KiB (0%)
Title                       : Full
Language                    : Russian
Default                     : No
Forced                      : No

Text #2
ID                          : 9
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 1 h 51 min
Bit rate                    : 34 b/s
Frame rate                  : 0.136 FPS
Count of elements           : 910
Stream size                 : 28.4 KiB (0%)
Title                       : Full
Language                    : English
Default                     : No
Forced                      : No

Text #3
ID                          : 10
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 1 h 59 min
Bit rate                    : 45 b/s
Frame rate                  : 0.191 FPS
Count of elements           : 1378
Stream size                 : 39.7 KiB (0%)
Title                       : SDH
Language                    : English
Default                     : No
Forced                      : No
```

**Comment by dmitrylyzo** [comment]
> [2024-09-03 20:40:15.259 +03:00] [ERR] [19] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/fcc2295f-be00-b7f2-af87-77fc0646074c/fcc2295fbe00b7f2af8777fc0646074c/Subtitles/8/0/Stream.js".
> System.ArgumentException: Unsupported format: srt

Could you [enable debug logging](https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging) on the server and retry with the browser?

There should be line `MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: Trying to parse '"srt"' subtitle using the "SubRip" format parser`.
Above it should be the subtitle path starting with `C:\ProgramData\Jellyfin\Server\data\subtitles\`.
Check if the file exists and is valid.

**Comment by Iowerth** [comment]
> Could you [enable debug logging](https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging) on the server and retry with the browser?
> 
> There should be line `MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: Trying to parse '"srt"' subtitle using the "SubRip" format parser`. Above it should be the subtitle path starting with `C:\ProgramData\Jellyfin\Server\data\subtitles\`. Check if the file exists and is valid.

The situation got stranger. Two movies that had no subtitles now have them both in browser and on TV.
Started a new movie for test - there are no subtitles both in browser and on TV (but they are displayed in MPC).

From debug log:
```
[2024-09-04 20:22:44.098 +03:00] [ERR] [21] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/f216b761-4061-f557-ad50-8ac4ff25cdfe/f216b7614061f557ad508ac4ff25cdfe/Subtitles/5/0/Stream.js".
System.ArgumentException: Unsupported format: srt
```
There are no lines that you have specified.

MediaInfo from new test movie:
```
Text #1
ID                          : 5
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 2 h 11 min
Bit rate                    : 1 b/s
Frame rate                  : 0.006 FPS
Count of elements           : 44
Stream size                 : 1.71 KiB (0%)
Title                       : forced
Language                    : Russian
Default                     : Yes
Forced                      : No

Text #2
ID                          : 6
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 2 h 12 min
Bit rate                    : 67 b/s
Frame rate                  : 0.161 FPS
Count of elements           : 1282
Stream size                 : 65.9 KiB (0%)
Title                       : FOCS
Language                    : Russian
Default                     : No
Forced                      : No

Text #3
ID                          : 7
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 1 h 49 min
Bit rate                    : 1 b/s
Frame rate                  : 0.006 FPS
Count of elements           : 38
Stream size                 : 954 Bytes (0%)
Title                       : forced
Language                    : English
Default                     : No
Forced                      : No

Text #4
ID                          : 8
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 2 h 12 min
Bit rate                    : 39 b/s
Frame rate                  : 0.164 FPS
Count of elements           : 1306
Stream size                 : 38.8 KiB (0%)
Title                       : full
Language                    : English
Default                     : No
Forced                      : No

Text #5
ID                          : 9
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 2 h 13 min
Bit rate                    : 46 b/s
Frame rate                  : 0.204 FPS
Count of elements           : 1630
Stream size                 : 45.7 KiB (0%)
Title                       : SDH
Language                    : English
Default                     : No
Forced                      : No
```

**Comment by dmitrylyzo** [comment]
> Two movies that had no subtitles now have them both in browser and on TV.
> Started a new movie for test - there are no subtitles both in browser and on TV (but they are displayed in MPC).

Probably, since the subtitles are internal, the server needs to extract them (`Allow subtitle extraction on the fly` option). This process takes some time, so subtitles may not appear immediately, depending on the size of the media file. It does this once for each subtitle track. So next time you will see them immediately, unless there is an error.

There is SubtitleExtract plugin in the official repository. It pre-extracts subtitles from all media files.

> There are no lines that you have specified.

Something similar? About subtitle extraction.
There are currently bugs in the server:
- https://github.com/jellyfin/jellyfin/issues/12570
- And double string escaping.

**Comment by Iowerth** [comment]
> `Allow subtitle extraction on the fly` option

It was disabled by myself because there were no subs with it enabled. Now I turned it on, will see.
> There is SubtitleExtract plugin in the official repository. It pre-extracts subtitles from all media files.

I have it installed, it is written in the first post.
> Something similar? About subtitle extraction.

Nothing.

Is it possible to extract subtitle for specific file only? Because if `Extract subtitles during library scan` enabled then it take too much time to re-scan a whole library.

**Comment by dmitrylyzo** [comment]
> Is it possible to extract subtitle for specific file only?

With `Allow subtitle extraction on the fly` enabled, it will extract subtitles only for the currently playing item.

But currently it may not work due to the mentioned bug. I think there should be error messages in the log in this case.

> Because if `Extract subtitles during library scan` enabled then it take too much time to re-scan a whole library.

I could be wrong, but it shouldn't try to re-extract existing subtitles.

**Comment by Iowerth** [comment]
Ok, thank you for helping as much as you can and sorry for the inconvenience. I think we can stop at this point, as it is taking too much time for both of us. I will be using external subtitles - thanks to gMKVExtractGUI, it only takes a few seconds.

You may close this issue, if there is nothing else to do.

**Comment by ganda234** [comment]
I'm having the exact the same issue. The weird part about this is that it plays well on 1080p movies. I've tried extract on the fly and the subtitle extract plugin. On 4k movies none of the subtitles work. The only workaround on this is to use external subtitles on the same folder as the movie.

```
[2024-09-04 17:14:31.032 +01:00] [ERR] [58] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/fe070472-e832-32a1-7b5f-90c68a451b8c/fe070472e83232a17b5f90c68a451b8c/Subtitles/4/0/Stream.js".
System.ArgumentException: Unsupported format: srt
```

```
[2024-09-08 02:35:21.253 +01:00] [INF] [24] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.11" playing "Little Fish". Stopped at "0" ms
[2024-09-08 02:35:23.361 +01:00] [INF] [26] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2024-09-08 02:35:26.360 +01:00] [INF] [27] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.11" playing "Little Fish". Stopped at "0" ms
[2024-09-08 02:35:33.583 +01:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2024-09-08 02:36:07.795 +01:00] [INF] [26] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.11" playing "Little Fish". Stopped at "133213" ms
```

TV model: LG 55UQ81006LB, software version 04.41.39

Media info:
[Incendies.2010.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.DTS-HD.MA.5.1-CiNEPHiLES.mkv_MediaInfo.txt](https://github.com/user-attachments/files/16920431/Incendies.2010.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.DTS-HD.MA.5.1-CiNEPHiLES.mkv_MediaInfo.txt)
[Little.Fish.2020.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv_MediaInfo.txt](https://github.com/user-attachments/files/16920433/Little.Fish.2020.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv_MediaInfo.txt)

Subtitles format: .srt

Playback method (DirectPlay, Remux, DirectStream, Transcode): Direct Play

**Comment by Iowerth** [comment]
@ganda234 hmm, this is an important note about 4K and 1080p. All I faced was 4K, I need to test on 1080p files just for no reason. But I can only do this only a week later because of vacation.

**Comment by dmitrylyzo** [comment]
`Unsupported format: srt` (from [here](https://github.com/jellyfin/jellyfin/blob/7bbdfc0d4943b1823d82cb85795a707a6e3a9b4d/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs#L67)) seems to happen when it can't parse the file.

With [debug level logging](https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging), you should see `MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: Trying to parse '"srt"' subtitle using the "SubRip" format parser` just before that line.

In case of an error there will be `... errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser`.
If still no such line, then there's no any subtitle parser for some reason.

@ganda234 is your server also on Windows?

**Comment by ganda234** [comment]
Yes, my server is also on windows
Just tried with debugg logging and there is no such lines, only `Unsupported format: srt`

```
[2024-09-09 01:00:39.257 +01:00] [ERR] [23] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/fe070472-e832-32a1-7b5f-90c68a451b8c/fe070472e83232a17b5f90c68a451b8c/Subtitles/5/0/Stream.js".
System.ArgumentException: Unsupported format: srt
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser.Parse(Stream stream, String fileExtension)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ConvertSubtitles(Stream stream, String inputFormat, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.GetSubtitle(Guid routeItemId, String routeMediaSourceId, Int32 routeIndex, String routeFormat, Nullable`1 itemId, String mediaSourceId, Nullable`1 index, String format, Nullable`1 endPositionTicks, Boolean copyTimestamps, Boolean addVttTimeMap, Int64 startPositionTicks)
   at lambda_method1152(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

```

**Comment by dmitrylyzo** [comment]
> Just tried on "Incendies" with debug logging and there is no such lines, only `Unsupported format: srt`

😕
Do you see any `[DBG]` marked lines? Just to make sure debugging is active.

**Comment by ganda234** [comment]
I though that debugging was on when trying the last time but it actually wasn't, tried again with it actually working:

```
[2024-09-09 16:03:27.253 +01:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False
[2024-09-09 16:03:27.259 +01:00] [DBG] [13] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "E:\Filmes\Incendies.2010.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.DTS-HD.MA.5.1-CiNEPHiLES.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2024-09-09 16:03:27.279 +01:00] [DBG] [13] Jellyfin.Api.Helpers.MediaInfoHelper: DirectPlay Result for Profile: "Anonymous Profile", Path: "E:\Filmes\Incendies.2010.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.DTS-HD.MA.5.1-CiNEPHiLES.mkv", PlayMethod: DirectPlay, AudioStreamIndex: 3, SubtitleStreamIndex: 5, Reasons: 0
[2024-09-09 16:03:27.284 +01:00] [DBG] [13] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="E:\Filmes\Incendies.2010.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.DTS-HD.MA.5.1-CiNEPHiLES.mkv", AudioStreamIndex=3, SubtitleStreamIndex=5 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/fe070472-e832-32a1-7b5f-90c68a451b8c/stream.mkv?MediaSourceId=fe070472e83232a17b5f90c68a451b8c&Static=true&VideoCodec=hevc&AudioCodec=ac3&AudioStreamIndex=3&api_key=<token>&Tag=663b873aa6ec2f73dde62719d649d1a1"
[2024-09-09 16:03:27.983 +01:00] [DBG] [15] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2024-09-09 16:03:28.413 +01:00] [DBG] [13] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-09-09 16:03:39.984 +01:00] [DBG] [10] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2024-09-09 16:03:40.769 +01:00] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-09-09 16:03:40.773 +01:00] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-09-09 16:03:44.510 +01:00] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-09-09 16:03:44.513 +01:00] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-09-09 16:03:51.533 +01:00] [DBG] [18] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-09-09 16:03:51.641 +01:00] [DBG] [18] MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-09-09 16:03:51.646 +01:00] [ERR] [18] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/fe070472-e832-32a1-7b5f-90c68a451b8c/fe070472e83232a17b5f90c68a451b8c/Subtitles/5/0/Stream.js".
System.ArgumentException: Unsupported format: srt
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser.Parse(Stream stream, String fileExtension)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ConvertSubtitles(Stream stream, String inputFormat, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SubtitleController.GetSubtitle(Guid routeItemId, String routeMediaSourceId, Int32 routeIndex, String routeFormat, Nullable`1 itemId, String mediaSourceId, Nullable`1 index, String format, Nullable`1 endPositionTicks, Boolean copyTimestamps, Boolean addVttTimeMap, Int64 startPositionTicks)
   at lambda_method1164(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
```

**Comment by dmitrylyzo** [comment]
> tried again with it actually working:

So it is actually trying to parse the file. Since there's no parse error, maybe file is just empty (extaction failed earlier)?

Subtitles are extracted to `C:\ProgramData\Jellyfin\Server\data\subtitles`, but they have [non-obvious names](https://github.com/jellyfin/jellyfin/blob/0d85af019c6ebc855ab2d8e689abe72b995225b4/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L839).
_I think we need another debug message indicating the path that is being processed._

**Comment by ganda234** [comment]
Went to check and I can confirm that there are subtitles on the folder, maybe their names should be more direct as you mentioned?

<img src="https://github.com/user-attachments/assets/eefc89a2-3c0c-405b-add1-870a38c73036" width=600>
<img src="https://github.com/user-attachments/assets/6ae6520f-c966-48de-b4f5-2ad3d3dee1af" width=600>

**Comment by Iowerth** [comment]
Are there any news? Subtitles still not showing.

**Comment by josch88** [comment]
Same here with the error in the log file „ Unsupported format: srt“.
Anyone working on this?
