### ISSUE TITLE
[bug] 10.6 webos app not loading pictures and info

### ISSUE THREAD

**Issue by Jonas2903** [jellyfin/jellyfin-webos#29]
I updated today to Jellyfin 10.6 and run on Debian 10 using Docker (Host) without Baseurl. Before the update everything worked fine. After the update no pictures are loading and no movie information are loading. Navigating is working and start playing something over the web UI is working too. Even the information are loaded while playing (rating, date). The order of the startmenu is not loading too. 
I build the webos app first myself and now reinstalled it and cleared cache on the TV. I tried to use the pre-build app but no luck with that. 

The only request I can find on the log for that is:
`
[2020-07-20 15:50:37.334 +00:00] [INF] [24] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:192.168.0.176" request
[2020-07-20 15:50:38.013 +00:00] [WRN] [12] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.0.176". Time (slow): 0:00:00.6713152. "http://192.168.0.100:8096/DisplayPreferences/usersettings?userId=1e23fe1616e041699de38f8139d90c55&client=emby"
`

![20200720_173408](https://user-images.githubusercontent.com/49312432/87958627-0e3ba200-cab2-11ea-85ea-827dc8b66091.jpg)

**Comment by Tyri0n** [comment]
I had the same after changing mac server to 10.6. Tried changing back to 10.5.5b but that no longer works now - logs say user not found. Not enough of ui appears to change user, though. Same results if tried in tv browser.

MediaBrowser.Common.Extensions.ResourceNotFoundException: User not found
   at MediaBrowser.Api.UserService.Get(GetUser request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-07-20 15:36:45.479 +01:00] [ERR] [19] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.68:8096/Users/edc555f6e05a44c4a0ed22f2b4df882c"

**Comment by oddstr13** [comment]
The app browser console and network logs would most likely contain useful information.

**Comment by Tyri0n** [comment]
Just remembers - 10.6 worked fine when connecting to from Windows Firefox.

**Comment by Jonas2903** [comment]
This is my debug console in chromium with webos IDE (filtered just errors):

`
180 messages are hidden by filters. Show all messages.
Failed to load resource: net::ERR_CACHE_MISS http://192.168.0.100:8096/web/index.html#!/home.html
error checking ScrollToOptions support scrollManager.js?v=20:1
RequireJS error: TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.. Failed modules:  site.js:1
Unhandled promise rejection TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method. bundle.js?v=20:252
2Failed to load resource: net::ERR_CACHE_MISS http://192.168.0.100:8096/web/index.html#!/home.html
`

**Comment by MrTimscampi** [comment]
@Jonas2903 Which version of WebOS are you on, please? (There is a reason we have issue templates, that info helps us track down the issues :) )

**Comment by Tyri0n** [comment]
> 
> 
> @Jonas2903 Which version of WebOS are you on, please? (~There is a reason we have issue templates, that info helps us track down the issues :)~ ) We don't have templates in this repo, nevermind)

3.3.4-3718 (dreadlocks-dharug)

**Comment by Jonas2903** [comment]
Sorry I forgot to mention that. I have 3.3.5-4518 (dreadlocks-dharug)

**Comment by MrTimscampi** [comment]
Thanks, we'll look into it for 10.6.1 :)

**Comment by Smoit** [comment]
Hi, I have the same problem. My server runs under Windows and my version of WebOS is 3.8.0-61208 (dreadlocks2-dunggir)

**Comment by oddstr13** [comment]
I can confirm that this is also an issue in the browser on webOS 3.3.4

**Comment by oddstr13** [comment]
Also reproducible in the emulator browser:
![image](https://user-images.githubusercontent.com/638706/88236003-5a3a4280-cc7c-11ea-9c5b-ed565e28657e.png)
